[project]
name = "qdrant-odm"
version = "0.0.1"
description = "Object-Document Mapping Library for Qdrant"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "qdrant-client>=1.12.1",
]
